# Check for broken links
name: Link Checker

on:
  push:
    branches:
      - feat/link-checker
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # Check every Sunday at midnight
    - cron: "00 00 * * 0"

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          cd website
          yarn install
          npm run build

      # Check links after build 
      - name: Link Checker
        uses: lycheeverse/lychee-action@v1.0.8
        with:
          args: --verbose --no-progress website/build/academy/**/*.html
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      # Check links before build

      # - name: Link Checker
      #   uses: lycheeverse/lychee-action@v1.0.8
      #   with:
      #     args: --verbose --no-progress docs/**/*.md
      #   env:
      #     GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Create Issue From File
        uses: peter-evans/create-issue-from-file@v3
        with:
          title: Link Checker Report
          content-filepath: ./lychee/out.md
          labels: report, automated issue
